---
- hosts: localhost
  connection: local

  tasks:

  - name: Create .vim directory
    file: path={{item}} state=directory mode=0755
    with_items:
      - ~/.vim
      - ~/.config/nvim

  - name: Check out Solarized color scheme for VIM
    git:
      repo: git@github.com:vim-scripts/Solarized.git
      dest: ~/.vim/plugged/Solarized/
      accept_hostkey: yes

  - name: Install Vim plugins for first time
    command: vim +PlugUpdate +qall!

  - name: Setup Vim config files
    file: src=~/src/65843/{{item.SRC}} dest={{item.DEST}} state=link
    with_items:
      - {SRC: gitconfig,   DEST: ~/.gitconfig}
      - {SRC: ansible.cfg, DEST: ~/.ansible.cfg}
      - {SRC: vimrc,       DEST: ~/.vimrc}
      - {SRC: autoload,    DEST: ~/.vim/autoload}
      - {SRC: vimrc,       DEST: ~/.config/nvim/init.vim}
      - {SRC: autoload,    DEST: ~/.config/nvim/autoload}

  - name: Link plugged directory to neovim
    file: src=~/.vim/plugged dest=~/.config/nvim/plugged state=link

  - name: Insall software for Arch/Manjaro
    pacman: name={{item}} state=latest
    when: ansible_distribution == "Archlinux" or ansible_distribution == "Manjaro Linux"
    become: true
    with_items:
      - dstat
      - git
      - lshw
      - neovim
      - pkgfile
      - ruby
      - the_silver_searcher
      - tree
      - vim
